# Generated by Django 2.1.7 on 2019-06-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='asd@asd', max_length=254, unique=True),
        ),
    ]
