# Generated by Django 2.1.7 on 2019-06-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190623_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='asd@asd', max_length=254),
        ),
    ]
