# Generated by Django 2.1.7 on 2019-05-27 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(default='not filled', max_length=20)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='not filled', max_length=20)),
                ('detail', models.CharField(default='not filled', max_length=200)),
                ('state', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.IntegerField(default=0)),
                ('content', models.CharField(default='not filled', max_length=200)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Paper')),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Choice')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Paper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Question')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('avatar', models.ImageField(upload_to='avatar')),
                ('nickname', models.CharField(default='not filled', max_length=20)),
                ('studentid', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.IntegerField(default=0)),
                ('grade', models.CharField(default='not filled', max_length=20)),
                ('major', models.CharField(default='not filled', max_length=20)),
                ('email', models.CharField(default='not filled', max_length=20)),
                ('phone', models.CharField(default='not filled', max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
        ),
        migrations.AddField(
            model_name='submit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='paper',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Question'),
        ),
    ]
