# Generated by Django 2.1.7 on 2019-06-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
