# Generated by Django 2.1.7 on 2019-06-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0007_auto_20190625_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
