# Generated by Django 2.1.7 on 2019-06-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0009_auto_20190625_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='question_fill',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='question_select',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
