# Generated by Django 2.1.7 on 2019-06-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_select',
            name='mytype',
            field=models.IntegerField(choices=[('单选', 1), ('多选', 9)], default='单选'),
        ),
    ]
