# Generated by Django 2.1.7 on 2019-06-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_auto_20190624_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_select',
            name='mytype',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
