# Generated by Django 2.1.7 on 2019-06-25 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190623_0502'),
        ('paper', '0005_auto_20190624_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='creater',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
