# Generated by Django 2.1.7 on 2019-06-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0006_paper_creater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='creater',
            field=models.CharField(max_length=128),
        ),
    ]
